Algoritmo "2 - Média"

Var
   num1, num2, num3, num4, num5, resultado: real

Inicio
   escreval("Digite o primeiro número:")
   leia (num1)
   escreval("Digite o segundo número:")
   leia (num2)
   escreval("Digite o terceiro número:")
   leia (num3)
   escreval("Digite o quarto número:")
   leia (num4)
   escreval("Digite o quinto número:")
   leia (num5)
   
   resultado <- (num1 + num2 + num3 + num4 + num5)/5
   limpatela
   escreva("A média é", resultado)

Fimalgoritmo